annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Project Monitoring
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/release-name: rancher-project-monitoring
apiVersion: v2
appVersion: v0.79.0
dependencies:
- condition: grafana.enabled
  name: grafana
  repository: file://./charts/grafana
  version: 8.10.4
description: Collects several related Helm charts, Grafana dashboards, and Prometheus
  rules combined with documentation and scripts to provide easy to operate end-to-end
  Kubernetes cluster monitoring with Prometheus. Depends on the existence of a Cluster
  Prometheus deployed via Prometheus Operator
home: https://github.com/prometheus-operator/kube-prometheus
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- prometheus
- monitoring
maintainers:
- email: alexandre.lamarre@suse.com
  name: Alexandre
- email: joshua.meranda@suse.com
  name: Joshua
- email: dan.pock@suse.com
  name: Dan
name: rancher-project-monitoring
type: application
version: 0.5.0
