# Default values for rancher-monitoring-crd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  cattle:
    psp:
      enabled: false
    systemDefaultRegistry: ""

image:
  repository: rancher/kuberlr-kubectl
  tag: v6.0.0

nodeSelector: {}

tolerations: []
